### ISSUE TITLE
Make “recipients” field optional

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#10]
This was a size optimization and simplification proposed in the presentation “ACE/CORE requirements on COSE” https://www.ietf.org/proceedings/93/slides/slides-93-cose-6.pdf on slide 7, and illustrated by additional slides.  I’ll note that draft -06 is already part way down this road by defining a Direct Encryption mode in Section 12.1.  Also define Direct Signature and Direct HMAC data structures in which no “recipients” field is present, and that will go a long way towards making the simple cases simpler (and smaller).

Note that this is issue is related to the “Allow single wrapping for symmetric key encryption + signature” requirement from ACE/CORE on the same slide and the “include a key management structure only when needed” issue on slide 6 of the “COSE Key Issues And Choices” presentation at https://www.ietf.org/proceedings/93/slides/slides-93-cose-7.pdf.

**Comment by jimsch** [comment]
This was addressed by the addition of the encrypted data structure.

**Comment by jricher** [comment]
These issues were filed for the upcoming f2f discussion. Re opening.

**Comment by selfissued** [comment]
Jim, if you believe that this was addressed by the addition of the encrypted data structure, then please add examples to the draft of a signature with no recipients field and a MAC with no recipients field, demonstrating to implementers what those look like.  Those examples will be simpler than the current ones in C.3.1 and C.1.1, which do contain "recipients" information.  Thanks.

**Comment by jimsch** [comment]
There is now a MAC version cose-wg/cose-spec#112

**Comment by selfissued** [comment]
Thanks for adding the Mac0 structure.  It looks OK to me.
