### ISSUE TITLE
Retain text marked “Text from here to start of next section to be removed”

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#11]
What follows text marked “Text from here to start of next section to be removed” is typically a BNF-like specification of what the text in the section specified.  This is valuable reference material that aids in the understanding of the specification.  Rather than removing this text, retain it, and preface it with appropriate introductory text such as “The following describes the syntax of the data structures defined by this section:”.

**Comment by jimsch** [comment]
There’s a very clear consensus that the CDDL will be inline with the text and marked as non-normative examples. The drafts will reflect that.

 — Justin
