### ISSUE TITLE
Remove “counter signature” header parameter

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#12]
The “counter signature” header parameter in Section 3.1 seems like an unnecessary feature in a spec that should aspire to be minimal and light-weight.  If the spec needs to talk about counter-signatures at all, it should do so by recommending that applications take the original COSE object and use it as a payload in another one to implement a counter-signature.  I haven’t seen a common use case for this discussed on the list, and it certainly doesn’t seem to satisfy the 80/20 rule for whether it merits inclusion.  Section 4.3 (Counter Signatures) also either needs to be deleted as part of this edit or modified to say that you compute a counter signature by using a COSE object as a signature payload.

**Comment by obgm** [comment]
Concur. I presume that the counter signature was introduced to handle the case of intermediaries that (legally) change options of CoAP messages when forwarding them (e.g. forwarding proxy that creates a Uri-\* options from a Proxy-Uri options).
The solution to deal with changeable CoAP options such as Max-Age, Observe, etc. will most likely require encapsulating the original CoAP message into a COSE object and transfer this as a payload in one of the proposed CoAP-over-COSE messaging mechanisms anyway.

**Comment by jimsch** [comment]
Counter signature was actually introduced to deal with the subscription model of CoAP.  There is a potential need for the server providing the data store the ability to 1) validate that the Resource server provided the data, without being able to decrypt the data  2) to provide to the observers a statement that the data was received by the data store.  The goal was to not require a full two layer mapping of the message and this was done to try and avoid that.  It may also find some usage in terms of proxies doing counter signatures to say that it did come from a specific sub-network and give a greater amount of origination attestation.

**Comment by selfissued** [comment]
I'm certainly not against CoAP or other applications defining additional header parameters beyond those defined by the base COSE specification that they want to use via the IANA "COSE Header Parameters" registry.  But that's the mechanism that should be used for defining such application-specific parameters - not speculatively adding them to the base specification.

Even if possibly useful to multiple applications, that's still not sufficient justification to add it to the base spec.  Parameters registered in the IANA registry _are_ available for use by multiple applications - which part of the point of registering them.  But let's remove "counter signature" from the base spec now.

**Comment by jimsch** [comment]
Parked until OsCOAP has done their analysis

**Comment by fpalombini** [comment]
Following our analysis [posted to the mailing list](https://mailarchive.ietf.org/arch/msg/cose/AF_Mv2O-IEwDs_NETtRYHkdcrXw), we consider this parameter useful in the case Symmetric Ecnryption-Asymmetric Signature, that would otherwise be done by encapsulating a COSE_Encrypt in a COSE_Sign structure, causing a very large overhead, as presented at the IETF94 f2f meeting.

**Comment by jimsch** [comment]
Given that we have a solid use case for this parameter, it will remain in the document.

**Comment by selfissued** [comment]
4.5 of -09 says "An example of a proxy signature on a signature can be found in Appendix B.3.3." but https://tools.ietf.org/html/draft-ietf-cose-msg-09#appendix-B.3.3 is missing the example.  I would leave this issue open until the example showing how to use a proxy signature is added.
