### ISSUE TITLE
Remove example features not implemented in the specification

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#15]
The description of the signing structure in Section 4 includes this text “Examples of parameters about the content would be the type of content, when the content was created, and who created the content.”  This triggered this comment by Hannes: “Ensure that the list of examples only includes items which are implemented in this specification. Check the other places where such lists occur and ensure that they also follow this rule.”

I agree with Hannes that this sentence should be removed, since the specification doesn’t define these parameters.  Another reason to remove these examples is that they are examples of payload content, not cryptographic parameters.

**Comment by selfissued** [comment]
It is incorrect to categorize this as being complete, as the sentence in question that Hannes first objected to has not been removed.  4.1 still includes this text:

Examples of
   parameters about the signature would be the algorithm and key used to
   create the signature, when the signature was created, and a counter-
   signature.

Please remove it.

**Comment by jimsch** [comment]
These are all attributes that are defined in the document.  It is therefore completed

**Comment by selfissued** [comment]
Once issue #13 has been addressed, the creation time will not be defined in the document.  This issue should be resolved in coordination with #13.
