### ISSUE TITLE
Inconsistency between COSE key_ops and WebCrypto API and JOSE key_ops

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#17]
The COSE key_ops list in Section 7 (COSE Key Common Parameters) is missing the “deriveKey” and “deriveBits” operations defined by WebCrypto and JOSE and adds the “key agree” operation not present in either of the related specs.  Please change the COSE key_ops to align with WebCrypto and JOSE.

**Comment by jimsch** [comment]
See cose-wg/cose-spec#111

merge in the world view of the WebCrypto spec for key_ops
