### ISSUE TITLE
Describe rule determining when zero length fields are used versus when nil is used

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#19]
Zero length bit fields are used for some omitted content (such as for an unused “protected” field in Section 3 (Header Parameters) whereas nil values are used for others (such as for the “ciphertext” field in 12.1 (Direct Encryption)).  The specification should include a clear statement of the rule used to make these choices and clear rationale for the rule.  If the specification currently doesn’t obey the rule in all particulars, please make appropriate changes.

**Comment by jimsch** [comment]
There is a rule, and I have no problem with sharing it, however I do not see the point of putting the rule into the document.  
1. Item which can be removed and sent detached will either be a type or nil.
2. Items which are truly optional would be either a type or nil.  However I do not believe that any of these exist in the document.

**Comment by selfissued** [comment]
I thought of asking this question while reviewing the document because I kept being surprised by the different choices made in apparently similar situations.  I'd share the rule in the draft to help the choices make sense to implementers.  In my experience, the more implementers "get" the choices made in a spec, the less likely they are to deviate from them, either intentionally or through oversight.  Thanks.

**Comment by jimsch** [comment]
Given that there are only two generic location where this is currently done, I do not understand the benefit.  (There are protected headers and message content.)   I would be surprised if most developers cared about having a design reasoning.  The only population that I would expect to care about this would be people who design new items in the future.  As I said, the rule is really easy and it applies in exactly one case - message content.
