### ISSUE TITLE
Add symbolic annotations to all examples

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#24]
As described in slide 15 of the “COSE Key Issues And Choices” presentation at https://www.ietf.org/proceedings/93/slides/slides-93-cose-7.pdf, please add symbolic descriptions of all parameters used in examples, as well as retaining their numeric and binary representations.  Currently the examples are unintelligible without huge amounts of manual labor, pouring through CBOR and COSE constant definitions and encodings!

For instance, use this:

{
  1 (typ): 3 (MAC),
  2 (protected): h'a1016f4145532d434d41432d3235362f3634',
    ({1 (alg): “AES-CMAC-256/64”})

Rather than just this:

{
  1: 3,
  2: h'a1016f4145532d434d41432d3235362f3634',

**Comment by jimsch** [comment]
Parked until the new dumper code gets written

**Comment by jimsch** [comment]
Put in a first pass at the annotation.  It is messy but it needs to be looked at to determine what needs to be cleaned up better.  It is a requirement that one can build the tests from the output so the suggested format would not have worked, however https://datatracker.ietf.org/doc/draft-greevenbosch-appsawg-cbor-cddl/ has a new expanded version of diagnostic CDDL which is used here.
