### ISSUE TITLE
Acknowledgements Missing

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#25]
Please add an Acknowledgements section acknowledging by name those who have made significant contributions to the specification.

**Comment by jimsch** [comment]
Parked until the document is finished

**Comment by selfissued** [comment]
While an Acknowledgements section has been added, all it says is "This document is a product of the COSE working group of the IETF."  This does not satisfy the intent of having an Acknowledgments
section, which is to acknowledge by name those who have made significant contributions to the specification.  This is not only a standard practice and a common courtesy - it's the right thing to do.

Until this is done, it is incorrect to categorize this issue as "complete".

**Comment by jricher** [comment]
The section has been created, and it's up to the editor how to list the acknowledgements as they see fit (within reason). That said, during WGLC we will work with the editor to make sure the appropriate acknowledgement is given in the final document. 

Closing this issue.
