### ISSUE TITLE
Separate the nonce and IV header parameters

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#27]
The description of the “nonce” header parameter in Section 3.1 says that “This parameter holds either a nonce or Initialization Vector value.”  Is there a well-understood reason why both a nonce and an initialization vector will never both be needed in the same set of header parameters.  Unless such a reason can be documented, please create separate header parameters for “nonce” and “IV”.

**Comment by jimsch** [comment]
It is not clear that this makes sense.  In many cases the IV is described as a nonce value not an IV.  An example of this is GCM.  It depends on what one things a nonce is as oppose to an IV.   How would you characterize a nonce that is not trans-actional, and thus by your criteria it should be place in the content not the wrapper

**Comment by jimsch** [comment]
Part of pull request cose-wg/cose-spec#98
