### ISSUE TITLE
Consider moving the description of “signature with message recovery” to a non-normative appendix

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#31]
Given that COSE doesn’t specify any algorithms using “signature with message recovery”, I would suggest moving the description of it from Section 8 (Signature Algorithms) to a non-normative appendix.

**Comment by jimsch** [comment]
I did think about both removing this and moving it to the secondary document.  In the end I decided that this  information needs to be highlighted to people who are writing systems as there is a significant chance that a sig w/ recovery algorithm is going to be defined and the way that content is obtained has some very different characteristics from the normal appendix mode.
