### ISSUE TITLE
Elaborate on “if it is not used in the computation of the content key”

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#35]
Section 12.1 (Direct Encryption) says “The 'protected' field MUST be a zero length item if it is not used in the computation of the content key.”  It would probably be helpful to implementers to say when the “protected” field is and is not used in this computation when performing direct encryption.

**Comment by selfissued** [comment]
As far as I can tell, there was no action taken in response to this issue and it was not discussed on the list.  I therefore request that either the action taken be pointed out so that it can be reviewed or the issue be reopened.  Thank you.

**Comment by jimsch** [comment]
Addressed in the commit https://github.com/cose-wg/cose-spec/commit/d5e2de2a2df0765f62a9d77465ad272aa022a4f1.  The details are in the two sections following about if the field can be non-null and what it means to use the field.

**Comment by selfissued** [comment]
Reading the commit, I can't find the text you're referring to.  For instance, I searched for "null" and the string didn't appear in the commit.  Can you please quote the text you're referring to, Jim so I can review it?  Thanks.
