### ISSUE TITLE
Registry for media-types

### ISSUE THREAD

**Issue by jimsch** [cose-wg/cose-issues#4]
We have a field for media types to be placed in a message.

We either need to look at killing this, decide to say that it will really take strings or figure out how we want to do the registry for this so that we can make things smaller in the message transmission.

Options to be looked at in making this decisions:

tstr - use the current string from the media-types registry.
[tstr, tstr] - use an array and keep the types separated
[int, tstr] - change the top level to an integer but keep the lower level as a string
[int, (int/tstr)] - create a registry for the lower level (could potentially modify the existing registry)
(int / tstr) - create a registry for everything (could potentially modify the existing registry)
(tstr / [int, (int/tstr]) - Allows for having maximum flexibility in the future while letting us just use strings today (this or the first option is the "punt" option).

If we decide to do an integer registration for this, then we need to have some type of criteria for assigning values to the existing registry entries.

Personal opinion - there is a lot to be said for punting this issue down the road until we get some input from people who are going to need this feature.  One of the places we can do some soliciting of data is from the JOSE mailing list to see if anybody there is using the content type field that was defined for JOSE.   Until we get people who are creating specialized content for transport with COSE, I don't think we have enough information to answer this question.

**Comment by cose-ietf** [comment]
We already have the content-format registry that CoAP uses to map media types to integers.  (Strictly speaking there is a content coding in there as well, but that can mostly be ignored for our purposes.)

Grüße, Carsten

**Comment by jimsch** [comment]
I had not realized that there was a registry for this purpose already.  So the only question left is what should the syntax be.  I think that having the content encoding as part of the registry makes sense.  If one has text/plain then one still needs to know what the code page is for that text.

At this point I am planning on making the syntax for this field (int / tstr) where the integers come from the CoAP table and the strings from the normal media-types table.

**Comment by jimsch** [comment]
Addressed in pull request cose-wg/cose-spec#70
