### ISSUE TITLE
Order appendices by importance

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#40]
I would place the Examples appendix first (changing it from C to A), followed by CDDL Grammar (changing it from A to B), and move Three Levels of Recipient Information (currently B) to the end.

**Comment by jimsch** [comment]
Keeping examples last makes more sense in many cases.  It is easier to flip to the end of a document on paper or e-book than it is to flip to some random place before that.   Additionally, having smaller appendixes first makes finding things easier.
