### ISSUE TITLE
Additional inconsistency between “none” and “direct” terminology

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#44]
Issue #29 was incompletely addressed.  Some instances of "none" were changed to "direct" but some others were not.

Section 12.4.1 (ECDH) of draft -08 says "The key wrap algorithm can be 'none'" - rather than saying that the key wrap algorithm can be direct.  Table 17 also contains several remaining uses of "none".

**Comment by jimsch** [comment]
Direct is not a key wrap algorithm, it is a key management algorithm.  The use of none in this location rather than direct is very intentional.
