### ISSUE TITLE
Should the type of Partial IV be bstr like IV, rather than uint?

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#46]
In Table 1 of draft -08, the type of IV is bstr, whereas the type of Partial IV is uint.  Is there a reason for this inconsistency, or should it also be bstr?

Or given that the use of Partial IV is application specific, should any type desired by the application be allowed for its value?

**Comment by jimsch** [comment]
This question was asked of the OSCoAP people and I am waiting to hear back from them on it

**Comment by fpalombini** [comment]
For OSCOAP use case, the partial IV can be up to 8B, so Jim can you change its type to  bstr?
Thank you!
