### ISSUE TITLE
Add the statement: "COSE implementations only need to implement the features needed for the applications they are designed to support"

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#50]
JOSE included this statement in http://tools.ietf.org/html/rfc7515#section-7:  "JWS implementations only need to implement the features needed for the applications they are designed to support."  Please add a corresponding statement about COSE implementations.

Especially in light of COSE being targeted for constrained devices, we should be clear to implementers that you don't have to build the whole thing for it to be a legal COSE implementation - just the parts that you need.

**Comment by jimsch** [comment]
This should be covered in the new Application Guidance re-write

**Comment by selfissued** [comment]
OK - the Application Considerations Section now fulfills this ask - thanks.
