### ISSUE TITLE
make "alg" field optional

### ISSUE THREAD

**Issue by fpalombini** [cose-wg/cose-issues#51]
To optimize the message size, we'd like you to consider changing the text "This parameter MUST be present at each level of a signed, encrypted or authenticated message." in section 3.1. in order to make the parameter optional. You could follow this paragraph with a note about including the "alg" in the external aad in case it is not present.

**Comment by selfissued** [comment]
I am against making inclusion of the algorithm optional. Among other reasons, doing so would make support for crypto agility more problematic.
