### ISSUE TITLE
Tag Request Range for CBOR Tags

### ISSUE THREAD

**Issue by jimsch** [cose-wg/cose-issues#54]
Do we need to change the request range of CBOR Tags in the current document.  The current request is going to produce two byte tags.  It would be possible to request single byte tags for some of the structures.  However, it is equally possible that the untagged versions are going to be used and the content types are going to be carried in COaP.

**Comment by selfissued** [comment]
I strongly believe that we should use one-byte tags.  For COSE, size matters.

**Comment by cose-ietf** [comment]
Hi,

Can we foresee that we will need the space of 2 byte tags? If not I vote
for one byte tags.

//Samuel

**Comment by jimsch** [comment]
Yes - I am not sure that makes a great deal of sense.  There are 15 one byte tags left.  We would be requesting that we get assigned 7 of them, that is almost half of the remaining space.  While we may believe that security is a high usage item, it is not clear that all of these need to have one byte tags depending on how it is believe that they are going to be used.

As top level things, it might be that OSCoAP uses a CoAP content option and thus never tags.  Similarly the use of the content COSE header field would eliminate the need to have tagging on the COSE message object.

I think that the CoAP content option is going to be a 3 or 4 byte option so the idea of using 2 byte tags instead does not seem to be a big loss.  The COSE content option would be 2 or 3 bytes and thus a wash in size with 2 byte tags.  

It might also make sense to only ask for one byte tags for some items and not for others.   It might also make sense to not ask for a tag with the key structures lessening our request of the space. I thought that keys might get transported a lot in different protocols and thus having a common way of identified would be useful.  But I could be wrong on that.

It is unfortunate that we are currently making guesses without solid data to rely on for this.

**Comment by fpalombini** [comment]
I think it makes sense to request one-byte tags only for the structures that aim at minimizing the size to the smallest size possible, namely COSE_Sign1, COSE_Mac0 and COSE_Encrypted.

**Comment by cose-ietf** [comment]
fpalombini wrote:

> I think it makes sense to request one-byte tags only for the structures
> that aim at minimizing the size to the smallest size possible, namely
> COSE_Sign1, COSE_Mac0 and COSE_Encrypted.

+1

Grüße, Carsten

**Comment by cose-ietf** [comment]
Hello
I have a business partnership proposal for you. Contact me on my
personal email for more details please :
***@***.***


Regards
Saif
