### ISSUE TITLE
Define detached content

### ISSUE THREAD

**Issue by fpalombini** [cose-wg/cose-issues#58]
Could you add a definition of "detached content" for (at least) COSE_Sign1 and COSE_Mac0? Right now detached content is mentioned in the draft only for COSE_Encrypted and COSE_Enveloped. We would like to refer to "detached content" also for these other structures.

In practice, t would be enough to simply write: 
"If the payload is transported separately **(i.e. detached content)**, then a nil CBOR object is placed in this location and it is the responsibility of the application to ensure that it will be transported without changes."
in section 4.1 and 6.1

**Comment by jimsch** [comment]
I am not sure that I follow the request.  The current Mac0 text says

 If the payload is not present in the message, the application is required to supply the payload separately. The payload is wrapped in a bstr to ensure that it is transported without changes. If the payload is transported separately, then a null CBOR object is placed in this location and it is the responsibility of the application to ensure that it will be transported without changes.

This does everything that you ask except for the "(i.e. detached content)" parenthetical aside. I have no problems with adding that, however I am more worried about the fact that you appear to think that the entire concept is not supported here.

**Comment by fpalombini** [comment]
No, I do see that the concept is supported. The request only meant adding that parenthesis to section 4.1 and 6.1 so that we can refer to the "detached content" of COSE from another document without having to explain what we mean by it, we can just reference the right sections.
