### ISSUE TITLE
Appendix A on Making Mandatory Items Optional is both unnecessary and empty

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#59]
Appendix A at https://tools.ietf.org/html/draft-ietf-cose-msg-10#appendix-A contains only this text:

Appendix A.  Making Mandatory Items Optional
A.1.  Algorithm Identification
A.2.  Countersignature Without Headers

It's an oxymoron to make mandatory items optional.  Therefore, this appendix should be deleted on that basis.  It's also devoid of content, and so not useful.

**Comment by jricher** [comment]
According to the editor, this will be addressed by the resolutions the both #51 and #52. Closing this issue as duplicate, with reference.
