### ISSUE TITLE
Algorithms: Should we have support for password based algorithms

### ISSUE THREAD

**Issue by jimsch** [cose-wg/cose-issues#6]
JOSE has support for password based algorithms mainly for the purpose of saving private keys for later use.  Given that we do not know what the introduction model for small devices is going be and given that many small devices do not have UI to enter a password, does it makes sense for use to skip having password based algorithms on the first pass of COSE.  They can always be added at a later time if they are needed.

**Comment by cose-ietf** [comment]
+1, I cannot se any use cases where this would be needed.

**Comment by jimsch** [comment]
Removed from the draft
