### ISSUE TITLE
Define a key parameter for IV

### ISSUE THREAD

**Issue by jimsch** [cose-wg/cose-issues#61]
We currently have a partial IV which is defined as being combined with a base IV in order to build the IV used for a given message.  The question is should we defined a parameter which can be carried as part of a COSE key structure to contain this base IV value?

Input from people who advocated for the partial IV field is requested.  You may not be planning to use COSE Key structures which means it would not be material.  If you are then this might be a good thing to add.

**Comment by fpalombini** [comment]
I think it would definitely be useful to have an (optional) IV field in the COSE_Key structure. 

If it is not defined in COSE, it could still be defined by the application, as I assume you mean by writing:
* label => values
in COSE_Key CDDL definition.
If it is the case, I think there should be some text specifying that the application can define more fields. If it isn't and I interpreted the CDDL wrong, then I am even more strongly in favor of defining the IV field in COSE_Key, and removing (or explaining) that line of the CDDL COSE_Key structure.
