### ISSUE TITLE
Remove JOSE commentary

### ISSUE THREAD

**Issue by jricher** [cose-wg/cose-issues#7]
The current draft contains the text:

```
The author did not always agree with some of the decisions made by
 the JOSE working group.  Many of these decisions have been re-
 examined, and where it seems to the author to be superior or
 simpler, replaced.
```

The COSE working group is not about "fixing JOSE" in retrospect. This paragraph needs to be removed.

**Comment by jimsch** [comment]
This should have been fixed in the -04 release in that it has been modified.  However it was not removed.  Please see if the change deals with your issue.
